'use client';

import type { PlatePluginConfig } from 'platejs/react';

import {
  FontBackgroundColorPlugin,
  FontColorPlugin,
  FontFamilyPlugin,
  FontSizePlugin,
} from '@platejs/basic-styles/react';
import { KEYS } from 'platejs';

const options = {
  inject: { targetPlugins: [...KEYS.heading, KEYS.p] },
} satisfies PlatePluginConfig;

export const FontKit = [
  FontColorPlugin.configure({
    inject: {
      ...options.inject,
      nodeProps: {
        defaultNodeValue: 'black',
      },
    },
  }),
  FontBackgroundColorPlugin.configure(options),
  FontSizePlugin.configure(options),
  FontFamilyPlugin.configure({
    inject: {
      ...options.inject,
      nodeProps: {
        defaultNodeValue: 'Arial',
        validNodeValues: [
          'Andale Mono',
          'Arial',
          'Arial Black',
          'Arial Narrow',
          'Arial Rounded MT Bold',
          'Avant Garde',
          'Bahnschrift',
          'Baskerville',
          'Big Caslon',
          'Bodoni MT',
          'Book Antiqua',
          'Bookman',
          'Bradley Hand',
          'Brush Script MT',
          'Calibri',
          'Calisto MT',
          'Cambria',
          'Cambria Math',
          'Candara',
          'Cascadia Code',
          'Cascadia Mono',
          'Century',
          'Century Gothic',
          'Century Schoolbook',
          'Chalkboard',
          'Chalkboard SE',
          'Comic Sans MS',
          'Consolas',
          'Constantia',
          'Copperplate',
          'Corbel',
          'Courier',
          'Courier New',
          'Didot',
          'Ebrima',
          'Fira Code',
          'Fira Sans',
          'Franklin Gothic',
          'Franklin Gothic Medium',
          'Futura',
          'Gabriola',
          'Garamond',
          'Geist',
          'Geneva',
          'Georgia',
          'Georgia Pro',
          'Gill Sans',
          'Gill Sans MT',
          'Goudy Old Style',
          'Helvetica',
          'Helvetica Neue',
          'Herculanum',
          'Hoefler Text',
          'IBM Plex Mono',
          'IBM Plex Sans',
          'IBM Plex Serif',
          'Impact',
          'Ink Free',
          'Inter',
          'JetBrains Mono',
          'Lato',
          'Lucida Bright',
          'Lucida Calligraphy',
          'Lucida Console',
          'Lucida Fax',
          'Lucida Grande',
          'Lucida Handwriting',
          'Lucida Sans',
          'Lucida Sans Typewriter',
          'Lucida Sans Unicode',
          'Luminari',
          'Marker Felt',
          'Menlo',
          'Merriweather',
          'Microsoft Sans Serif',
          'Monaco',
          'Monotype Corsiva',
          'Montserrat',
          'MS Gothic',
          'MS PGothic',
          'MS Reference Sans Serif',
          'MS Sans Serif',
          'MS Serif',
          'Neucha',
          'Noto Mono',
          'Noto Sans',
          'Noto Serif',
          'Nunito',
          'Open Sans',
          'Optima',
          'Oswald',
          'Palatino',
          'Palatino Linotype',
          'Papyrus',
          'Perpetua',
          'Playfair Display',
          'Poppins',
          'PT Mono',
          'PT Sans',
          'PT Sans Narrow',
          'PT Serif',
          'Quicksand',
          'Raleway',
          'Rockwell',
          'Rockwell Extra Bold',
          'Roboto',
          'Roboto Condensed',
          'Roboto Mono',
          'Roboto Slab',
          'SF Mono',
          'SF Pro Display',
          'SF Pro Text',
          'Segoe Print',
          'Segoe Script',
          'Segoe UI',
          'Segoe UI Emoji',
          'Segoe UI Historic',
          'Segoe UI Symbol',
          'SignPainter',
          'Sitka',
          'Source Code Pro',
          'Source Sans Pro',
          'Source Serif Pro',
          'Space Mono',
          'Sylfaen',
          'Tahoma',
          'Times',
          'Times New Roman',
          'Trattatello',
          'Trebuchet MS',
          'Ubuntu',
          'Ubuntu Condensed',
          'Ubuntu Mono',
          'Verdana',
          'Webdings',
          'Wingdings',
          'Work Sans',
          'sans-serif',
          'serif',
          'monospace',
          'cursive',
          'fantasy',
        ],
      },
    },
  }),
];
